version: '3'
services:
  db:
    image: mysql:5.7.19
    ports:
      - "3306:3306" #MySQLが使うポート番号はデフォルトで3306
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/todo2
    ports:
      - "3035:3035"
  web:
    build: .
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/todo2
      - bundle-data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
volumes:
  bundle-data:
  db-data:
